import { runnerTag, type Ci } from '../../model/deployment'
import { devicesOf, type DeviceRole, type PartitionDevices } from '../devices'
import type { AnsibleContext } from './index'
import { fromObject, kv, toYaml, ymap, type YEntry, type YMap, type YValue } from './yaml'

// CI/CD pipelines that check and deploy the generated playbooks. GitLab is
// the first-class target (the layout of metal-stack deployment
// repositories: one image with Ansible, manual deploy jobs per partition
// in the order mgmt servers, mgmt network, prod network, one resource
// group per partition, runners tagged per partition because only a runner
// inside the partition reaches its management network); GitHub Actions
// gets the same as a check workflow and a dispatch-triggered deploy.
//
// Credentials never enter the repository: Ansible reads
// ANSIBLE_PRIVATE_KEY_FILE and ANSIBLE_VAULT_PASSWORD_FILE from the
// environment, which GitLab file variables and a GitHub step fill in.

export interface DeployStep {
  id: string
  label: string
  playbook: string
  roles: DeviceRole[]
}

/** Deploy order, as in the deployment repositories. */
export const DEPLOY_STEPS: DeployStep[] = [
  {
    id: 'mgmt-server',
    label: 'Management servers',
    playbook: 'deploy_mgmt_server.yaml',
    roles: ['mgmt-server'],
  },
  {
    id: 'mgmt-network',
    label: 'Management network',
    playbook: 'deploy_mgmt_network.yaml',
    roles: ['mgmt-spine', 'mgmt-leaf'],
  },
  {
    id: 'prod-network',
    label: 'Production network',
    playbook: 'deploy_prod_network.yaml',
    roles: ['superspine', 'spine', 'exit', 'storage-leaf', 'leaf'],
  },
]

/** Steps with devices in the partition. */
export function stepsFor(p: PartitionDevices): DeployStep[] {
  return DEPLOY_STEPS.filter((s) => s.roles.some((r) => devicesOf(p, r).length > 0))
}

const INSTALL = [
  'ansible-galaxy role install -r requirements.yaml -p roles',
  'ansible-galaxy collection install -r requirements.yaml',
]

const SYNTAX_CHECK = `ansible-inventory --graph > /dev/null
for playbook in deploy_*.yaml; do
  ansible-playbook --syntax-check "$playbook"
done
`

const NO_PLACEHOLDERS = `if grep -rn CHANGE_ME inventories; then
  echo "Fill in the CHANGE_ME values above before deploying."
  exit 1
fi
`

function ansibleEnv(ci: Ci): YEntry[] {
  return [
    kv('ANSIBLE_FORCE_COLOR', '1'),
    kv('ANSIBLE_HOST_KEY_CHECKING', ci.hostKeyChecking ? 'True' : 'False'),
    ...(ci.sshUser.trim() ? [kv('ANSIBLE_REMOTE_USER', ci.sshUser.trim())] : []),
  ]
}

const HEADER = 'Generated by the metal-stack planner.'

function gitlab({ plan, devices, out }: AnsibleContext): string {
  const ci = plan.deployment.ci
  const env = out.inventory.split('/')[1]
  const branchRule = `$CI_COMMIT_BRANCH == "${ci.branch}"`
  const jobs: YEntry[] = []
  for (const p of devices) {
    const tag = runnerTag(ci, p.partitionId, p.slug)
    const steps = stepsFor(p)
    if (steps.length === 0) continue
    const common = [kv('tags', [tag])]
    if (ci.dryRun) {
      jobs.push(
        kv(
          `${p.slug}:dry-run`,
          ymap(
            kv('extends', '.dry-run'),
            ...common,
            kv(
              'script',
              steps.map((s) => `ansible-playbook ${s.playbook} --limit ${p.group} --check --diff`),
            ),
          ),
          `${p.partitionName}: runners tagged "${tag}" must reach its management network.`,
        ),
      )
    }
    steps.forEach((s, i) => {
      const name = `${p.slug}:${i + 1}-${s.id}`
      jobs.push(
        kv(
          name,
          ymap(
            kv('extends', '.deploy'),
            ...common,
            kv('resource_group', p.slug),
            kv('environment', ymap(kv('name', `${env}/${p.slug}`))),
            kv('needs', [i === 0 ? 'check' : `${p.slug}:${i}-${steps[i - 1].id}`]),
            kv('script', [`ansible-playbook ${s.playbook} --limit ${p.group}`]),
          ),
          !ci.dryRun && i === 0
            ? `${p.partitionName}: runners tagged "${tag}" must reach its management network.`
            : undefined,
        ),
      )
    })
  }

  return toYaml(
    ymap(
      kv('image', ci.image),
      kv('stages', ['check', 'deploy']),
      kv('variables', ymap(...ansibleEnv(ci))),
      kv(
        'default',
        ymap(
          kv('before_script', [
            ...INSTALL,
            `if [ -n "\${ANSIBLE_PRIVATE_KEY_FILE:-}" ]; then chmod 600 "$ANSIBLE_PRIVATE_KEY_FILE"; fi
if [ -n "\${SSH_KNOWN_HOSTS:-}" ]; then mkdir -p ~/.ssh && cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts; fi
`,
          ]),
        ),
      ),
      kv(
        'check',
        ymap(kv('stage', 'check'), kv('script', [SYNTAX_CHECK, NO_PLACEHOLDERS])),
        'Inventory, playbook syntax and leftover placeholders, on every push.',
      ),
      kv(
        '.deploy',
        ymap(
          kv('stage', 'deploy'),
          kv('rules', [ymap(kv('if', branchRule), kv('when', 'manual'))]),
        ),
        `Deploys run by hand from ${ci.branch}, in order, one at a time per partition.`,
      ),
      ci.dryRun &&
        kv(
          '.dry-run',
          ymap(
            kv('stage', 'deploy'),
            kv('needs', ['check']),
            kv('rules', [ymap(kv('when', 'manual'))]),
            kv('allow_failure', true),
          ),
          'Shows what a deploy would change (--check --diff), from any branch.',
        ),
      ...jobs,
    ),
    `${HEADER}
CI/CD variables (Settings > CI/CD > Variables), type File, protected:
  ANSIBLE_PRIVATE_KEY_FILE     SSH private key for all hosts
  ANSIBLE_VAULT_PASSWORD_FILE  password of the ansible-vault encrypted secrets
  SSH_KNOWN_HOSTS              known_hosts entries of all hosts`,
  )
}

const expr = (e: string) => '${{ ' + e + ' }}'

function githubCheck({ plan }: AnsibleContext): string {
  const ci = plan.deployment.ci
  return toYaml(
    ymap(
      kv('name', 'Check'),
      kv('on', ymap(kv('push', ymap(kv('branches', [ci.branch]))), kv('pull_request', null))),
      kv(
        'jobs',
        ymap(
          kv(
            'check',
            ymap(
              kv('runs-on', 'ubuntu-latest'),
              kv('container', ci.image),
              kv('env', ymap(kv('ANSIBLE_FORCE_COLOR', '1'))),
              kv('steps', [
                fromObject({ uses: 'actions/checkout@v4' }),
                fromObject({
                  name: 'Install roles and collections',
                  run: INSTALL.join('\n') + '\n',
                }),
                fromObject({ name: 'Check inventory and playbooks', run: SYNTAX_CHECK }),
                fromObject({ name: 'No placeholders left', run: NO_PLACEHOLDERS }),
              ]),
            ),
          ),
        ),
      ),
    ),
    `${HEADER}\nInventory, playbook syntax and leftover placeholders, on every push.`,
  )
}

const CREDENTIALS = `umask 077
dir="$RUNNER_TEMP/ansible"
mkdir -p "$dir" ~/.ssh
printf '%s\\n' "$SSH_PRIVATE_KEY" > "$dir/id"
echo "ANSIBLE_PRIVATE_KEY_FILE=$dir/id" >> "$GITHUB_ENV"
if [ -n "$VAULT_PASSWORD" ]; then
  printf '%s\\n' "$VAULT_PASSWORD" > "$dir/vault"
  echo "ANSIBLE_VAULT_PASSWORD_FILE=$dir/vault" >> "$GITHUB_ENV"
fi
if [ -n "$KNOWN_HOSTS" ]; then
  printf '%s\\n' "$KNOWN_HOSTS" > ~/.ssh/known_hosts
fi
`

function githubDeploy({ plan, devices, out }: AnsibleContext): string {
  const ci = plan.deployment.ci
  const env = out.inventory.split('/')[1]
  const partitions = devices.filter((p) => stepsFor(p).length > 0)
  const inputs: YEntry[] = [
    kv(
      'partition',
      ymap(
        kv('description', 'Partition to deploy'),
        kv('type', 'choice'),
        kv('required', true),
        kv(
          'options',
          partitions.map((p) => p.slug),
        ),
      ),
    ),
    kv(
      'playbook',
      ymap(
        kv('description', 'Playbooks to run'),
        kv('type', 'choice'),
        kv('default', 'all'),
        kv('options', ['all', ...DEPLOY_STEPS.map((s) => s.id)]),
      ),
    ),
  ]
  if (ci.dryRun) {
    inputs.push(
      kv(
        'dry_run',
        ymap(
          kv('description', 'Dry run only (--check --diff)'),
          kv('type', 'boolean'),
          kv('default', true),
        ),
      ),
    )
  }
  const onBranch = `github.ref_name == '${ci.branch}'`
  const flags = ci.dryRun ? ` ${expr("inputs.dry_run && '--check --diff' || ''")}` : ''

  const job = (p: PartitionDevices): YMap => {
    const tag = runnerTag(ci, p.partitionId, p.slug)
    const allowed = ci.dryRun ? `(inputs.dry_run || ${onBranch})` : onBranch
    return ymap(
      kv('name', `Deploy ${p.slug}`),
      kv('if', `inputs.partition == '${p.slug}' && ${allowed}`),
      kv(
        'runs-on',
        ['self-hosted', tag],
        `Runners labeled "${tag}" must reach its management network.`,
      ),
      kv('environment', `${env}-${p.slug}`),
      kv('concurrency', ymap(kv('group', `deploy-${p.slug}`), kv('cancel-in-progress', false))),
      kv('container', ci.image),
      kv('steps', [
        fromObject({ uses: 'actions/checkout@v4' }),
        fromObject({
          name: 'Install credentials',
          env: fromObject({
            SSH_PRIVATE_KEY: expr('secrets.ANSIBLE_SSH_PRIVATE_KEY'),
            VAULT_PASSWORD: expr('secrets.ANSIBLE_VAULT_PASSWORD'),
            KNOWN_HOSTS: expr('secrets.SSH_KNOWN_HOSTS'),
          }),
          run: CREDENTIALS,
        }),
        fromObject({ name: 'Install roles and collections', run: INSTALL.join('\n') + '\n' }),
        ...stepsFor(p).map((s): YValue =>
          fromObject({
            name: s.label,
            if: `inputs.playbook == 'all' || inputs.playbook == '${s.id}'`,
            run: `ansible-playbook ${s.playbook} --limit ${p.group}${flags}`,
          }),
        ),
      ]),
    )
  }

  return toYaml(
    ymap(
      kv('name', 'Deploy'),
      kv('on', ymap(kv('workflow_dispatch', ymap(kv('inputs', ymap(...inputs)))))),
      kv('env', ymap(...ansibleEnv(ci))),
      kv('jobs', ymap(...partitions.map((p) => kv(p.slug.replace(/[^a-z0-9_-]/g, '-'), job(p))))),
    ),
    `${HEADER}
Run from Actions > Deploy. Deploys run from ${ci.branch}${ci.dryRun ? ', dry runs from any branch' : ''}.
Secrets (per environment ${partitions.map((p) => `${env}-${p.slug}`).join(', ')}):
  ANSIBLE_SSH_PRIVATE_KEY  SSH private key for all hosts
  ANSIBLE_VAULT_PASSWORD   password of the ansible-vault encrypted secrets
  SSH_KNOWN_HOSTS          known_hosts entries of all hosts`,
  )
}

/** Adds the pipeline files for the chosen platform(s). */
export function ciFiles(ctx: AnsibleContext): void {
  const { platform } = ctx.plan.deployment.ci
  if (platform === 'gitlab' || platform === 'both') ctx.out.add('.gitlab-ci.yml', gitlab(ctx))
  if (platform === 'github' || platform === 'both') {
    ctx.out.add('.github/workflows/check.yaml', githubCheck(ctx))
    ctx.out.add('.github/workflows/deploy.yaml', githubDeploy(ctx))
  }
}

/** README section on the pipelines. */
export function ciReadme({ plan, devices }: AnsibleContext): string[] {
  const ci = plan.deployment.ci
  if (ci.platform === 'none') return []
  const lines = ['## CI/CD', '']
  const runners = devices
    .filter((p) => stepsFor(p).length > 0)
    .map((p) => `\`${runnerTag(ci, p.partitionId, p.slug)}\` (${p.partitionName})`)
  lines.push(
    `Every push runs the check (inventory, playbook syntax, no \`CHANGE_ME\` left). Deploys are`,
    `started by hand from \`${ci.branch}\` and run per partition in the order management servers,`,
    'management network, production network. They need a runner inside each partition, one that',
    `reaches its management network, tagged ${runners.join(', ')}. Bootstrap the first`,
    'management server from a workstation, as its runner usually lives there.',
    '',
  )
  if (ci.platform !== 'github') {
    lines.push(
      '**GitLab** (`.gitlab-ci.yml`): add the CI/CD variables `ANSIBLE_PRIVATE_KEY_FILE`,',
      '`ANSIBLE_VAULT_PASSWORD_FILE` and `SSH_KNOWN_HOSTS` as protected variables of type File.',
      '',
    )
  }
  if (ci.platform !== 'gitlab') {
    lines.push(
      '**GitHub Actions** (`.github/workflows/`): add the secrets `ANSIBLE_SSH_PRIVATE_KEY`,',
      '`ANSIBLE_VAULT_PASSWORD` and `SSH_KNOWN_HOSTS` to each deploy environment and register',
      'self-hosted runners with the labels above; run Actions > Deploy.',
      '',
    )
  }
  return lines
}
