import type { Nos } from '../../model/plan'
import type { DeviceRole, PartitionDevices } from '../devices'
import type { AnsibleContext } from './index'
import { kv, toYaml, ymap, type YEntry, type YMap } from './yaml'

// inventory.yaml: functional groups (leaves, spines …) across partitions,
// each with one child group per partition, and per partition a group
// holding those children, the leaves split into one group per rack. This
// is the layout of metal-stack deployment repositories: group_vars can
// target a device kind everywhere, one partition, or one rack.

/** Functional group per device role, in inventory order. */
export const ROLE_GROUP: Record<DeviceRole, string> = {
  'mgmt-server': 'mgmtservers',
  'mgmt-leaf': 'mgmtleaves',
  'mgmt-spine': 'mgmtspines',
  router: 'inet',
  leaf: 'leaves',
  spine: 'spines',
  superspine: 'superspines',
  exit: 'exits',
  'storage-leaf': 'storageleaves',
}

const ROLES = Object.keys(ROLE_GROUP) as DeviceRole[]

export const partitionGroup = (p: PartitionDevices, role: DeviceRole) =>
  `${p.group}_${ROLE_GROUP[role]}`

export const rackGroup = (p: PartitionDevices, tag: string) => `${p.group}_${tag}`

const hosts = (names: string[]): YMap => ymap(...names.map((n) => kv(n, null)))

function partitionEntry(p: PartitionDevices): YEntry {
  const children = ROLES.flatMap((role): YEntry[] => {
    const list = p.devices.filter((d) => d.role === role)
    if (list.length === 0) return []
    if (role !== 'leaf') {
      return [kv(partitionGroup(p, role), ymap(kv('hosts', hosts(list.map((d) => d.hostname)))))]
    }
    const racks = p.racks
      .map((r) => ({ r, names: list.filter((d) => d.rack?.rackId === r.rackId) }))
      .filter(({ names }) => names.length > 0)
      .map(({ r, names }) =>
        kv(rackGroup(p, r.tag), ymap(kv('hosts', hosts(names.map((d) => d.hostname)))), r.name),
      )
    return [kv(partitionGroup(p, role), ymap(kv('children', ymap(...racks))))]
  })
  return kv(p.group, ymap(kv('children', ymap(...children))), p.partitionName)
}

/** Switch roles, grouped by the partition's NOS. */
export const SWITCH_ROLES: DeviceRole[] = [
  'mgmt-leaf',
  'mgmt-spine',
  'leaf',
  'spine',
  'superspine',
  'exit',
  'storage-leaf',
]

/** NOS groups: which switches sonic-config configures (Edgecore SONiC) and
 *  which the Dell collection (Broadcom SONiC). */
export const NOS_GROUP: Record<Nos, string> = {
  'edgecore-sonic': 'edgecore_sonic',
  'broadcom-sonic': 'broadcom_sonic',
}

export function inventoryFile({ plan, devices, out }: AnsibleContext): void {
  const functional = ROLES.map((role) => {
    const members = devices
      .filter((p) => p.devices.some((d) => d.role === role))
      .map((p) => kv(partitionGroup(p, role), null))
    return kv(ROLE_GROUP[role], members.length ? ymap(kv('children', ymap(...members))) : ymap())
  })
  const nosGroups = (Object.keys(NOS_GROUP) as Nos[])
    .map((nos) => {
      const members = devices
        .filter((_, i) => plan.partitions[i].fabric.nos === nos)
        .flatMap((p) =>
          SWITCH_ROLES.filter((role) => p.devices.some((d) => d.role === role)).map((role) =>
            kv(partitionGroup(p, role), null),
          ),
        )
      return members.length > 0 && kv(NOS_GROUP[nos], ymap(kv('children', ymap(...members))))
    })
    .filter((e): e is YEntry => !!e)
  out.add(
    `${out.inventory}/inventory.yaml`,
    toYaml(
      ymap(
        kv(
          'all',
          ymap(
            kv(
              'children',
              ymap(
                kv(
                  'partition',
                  ymap(
                    kv(
                      'children',
                      ymap(...functional, ...nosGroups, ...devices.map(partitionEntry)),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      'Generated by the metal-stack planner. Hosts are named after the plan;\nansible_host comes from host_vars (the management addresses).',
    ),
  )
}
