import { ANSIBLE_COMMON_REPO, METAL_ROLES_REPO } from '../../model/ansibleRoles'
import { formatCidr, formatIp } from '../ip/cidr'
import type { AnsibleContext } from './index'
import { fromObject, kv, toYaml, toYamlSeq, ymap, type YValue } from './yaml'

// Playbooks, role requirements, ansible.cfg and the README of the Ansible
// export. The plays follow mini-lab's deploy_partition.yaml and the
// deployment repositories: sonic-config on every switch, metal-core on the
// leaves, the management server roles on the mgmt servers.

const role = (name: string, tags?: string): YValue => fromObject(tags ? { name, tags } : { name })

/** Collections the targeted metal-roles and ansible-common need. */
const COLLECTIONS = ['community.docker', 'community.general', 'ansible.posix', 'ansible.utils']

const INSTALL = [
  'ansible-galaxy role install -r requirements.yaml -p roles',
  'ansible-galaxy collection install -r requirements.yaml',
]

const COMMON = role('ansible-common', 'always')
const SONIC = role('metal-roles/partition/roles/sonic-config', 'sonic-config')

function play(name: string, hosts: string, roles: YValue[], extra: Record<string, YValue> = {}) {
  return fromObject({ name, hosts, ...extra, roles })
}

export function staticFiles({ plan, out }: AnsibleContext): void {
  const dep = plan.deployment
  const header = 'Generated by the metal-stack planner.'
  out.add(
    'ansible.cfg',
    [
      '# Generated by the metal-stack planner.',
      '[defaults]',
      `inventory = ${out.inventory}/inventory.yaml`,
      'roles_path = roles',
      '',
    ].join('\n'),
  )
  out.add(
    'requirements.yaml',
    toYaml(
      ymap(
        kv('roles', [
          fromObject({
            src: ANSIBLE_COMMON_REPO,
            name: 'ansible-common',
            version: dep.ansibleCommonVersion,
          }),
          fromObject({
            src: METAL_ROLES_REPO,
            name: 'metal-roles',
            version: dep.metalRolesVersion,
          }),
        ]),
        kv(
          'collections',
          COLLECTIONS.map((name) => fromObject({ name })),
          'Modules the roles call (docker containers, timezone, sysctl, IP filters).',
        ),
      ),
      `${header}\n${INSTALL.join('\n')}`,
    ),
  )
  out.add(
    'deploy_prod_network.yaml',
    toYamlSeq(
      [
        play(
          'Configure superspines, spines, exits and storage leaves',
          'superspines:spines:exits:storageleaves',
          [COMMON, SONIC],
          { serial: 1 },
        ),
        play('Configure leaves', 'leaves', [COMMON, SONIC], { serial: 1 }),
        play(
          'Deploy metal-core',
          'leaves',
          [COMMON, role('metal-roles/partition/roles/metal-core', 'metal-core')],
          { serial: 1, become: true },
        ),
      ],
      header,
    ),
  )
  out.add(
    'deploy_mgmt_network.yaml',
    toYamlSeq(
      [play('Configure management switches', 'mgmtspines:mgmtleaves', [COMMON, SONIC])],
      header,
    ),
  )
  out.add(
    'deploy_mgmt_server.yaml',
    toYamlSeq(
      [
        play(
          'Deploy management servers',
          'mgmtservers',
          [
            COMMON,
            role('metal-roles/partition/roles/mgmt-server', 'mgmt-server'),
            role('metal-roles/partition/roles/dhcp', 'dhcp'),
            role('metal-roles/partition/roles/metal-bmc', 'metal-bmc'),
            role('metal-roles/partition/roles/pixiecore', 'pixiecore'),
            role('metal-roles/partition/roles/image-cache', 'image-cache'),
          ],
          { become: true },
        ),
      ],
      header,
    ),
  )
}

const row = (cells: (string | number)[]) => `| ${cells.join(' | ')} |`

export function readme({ plan, devices, addresses, out }: AnsibleContext, notes: string[]): string {
  const lines: string[] = [
    `# ${plan.name}: metal-stack partition deployment`,
    '',
    'Generated by the metal-stack planner from the plan. Hostnames, ASNs, loopbacks,',
    'management addresses, PXE networks and DHCP ranges are derived; everything the',
    'plan cannot know is marked `CHANGE_ME` and listed below.',
    '',
    '## Usage',
    '',
    '```sh',
    ...INSTALL,
    'ansible-playbook deploy_mgmt_network.yaml',
    'ansible-playbook deploy_mgmt_server.yaml',
    'ansible-playbook deploy_prod_network.yaml',
    '```',
    '',
    `The inventory is \`${out.inventory}/inventory.yaml\` (set in \`ansible.cfg\`).`,
    'Encrypt `group_vars/partition/secrets.yaml` with `ansible-vault` once filled in.',
    '',
  ]
  if (out.placeholders.length > 0) {
    lines.push('## To fill in', '', row(['File', 'Variable', 'What']), row(['---', '---', '---']))
    for (const p of out.placeholders) lines.push(row([`\`${p.file}\``, `\`${p.key}\``, p.reason]))
    lines.push('')
  }
  if (notes.length > 0) {
    lines.push('## Address plan warnings', '', ...notes.map((n) => `- ${n}`), '')
  }
  devices.forEach((p, i) => {
    const addr = addresses[i]
    lines.push(
      `## ${p.partitionName} (\`${p.slug}\`)`,
      '',
      row(['Host', 'Role', 'ASN', 'Loopback', 'Management']),
      row(['---', '---', '---', '---', '---']),
    )
    for (const d of p.devices) {
      const a = addr.byHost.get(d.hostname)!
      lines.push(
        row([
          d.hostname,
          d.role,
          d.asn ?? '–',
          a.loopback ?? '–',
          a.mgmt ? `${a.mgmt.ip}/${a.mgmt.prefix}` : '–',
        ]),
      )
    }
    if (addr.mgmtSubnets.length > 0) {
      lines.push('', row(['Management subnet', 'Scope', 'Gateway']), row(['---', '---', '---']))
      for (const s of addr.mgmtSubnets) {
        lines.push(row([formatCidr(s.cidr), s.scope, formatIp(4, s.gateway)]))
      }
    }
    lines.push('')
  })
  return lines.join('\n')
}
