import { deriveInventory, MISSING_INPUTS } from '../derive/deploy/inventory'
import { nosLabel } from '../model/catalog'
import type { Plan } from '../model/plan'
import { toYaml } from './yaml'

// The Ansible inventory export: the derived inventory as YAML, behind a
// comment header that says what it was written against and what it still
// lacks. The same plan always gives the same bytes (no timestamp), so the
// file diffs cleanly in a deployment repository.

/** metal-roles release the variable names were checked against. */
export const METAL_ROLES_VERSION = 'v0.35.0'

export interface AnsibleExport {
  text: string
  problems: string[]
}

function header(plan: Plan): string {
  const nos = [...new Set(plan.partitions.map((p) => nosLabel(p.fabric.nos)))].join(', ')
  const lines = [
    `Ansible inventory for "${plan.name}", generated by metal-stack planner.`,
    `Variable names follow metal-roles ${METAL_ROLES_VERSION} (sonic-config, metal-core,`,
    'mgmt-server, dhcp, pixiecore, ztp); planner_* variables only document the plan,',
    'planner_ports being the cable plan of each device.',
    '',
    `Switch OS in the plan: ${nos}. The sonic-config role is tested against Edgecore`,
    'SONiC 202111.x and 202211.x; metal-core needs sonic_config_docker_routing_config_mode',
    '"split" there (the role default).',
    '',
    ...(plan.partitions.some((p) => p.fabric.fabricType === 'leaf-spine-superspine')
      ? [
          'Leaf-spine-superspine partitions follow RFC 7938 (pods and planes), a planning',
          'design and not a metal-stack reference architecture. Their variables are',
          'UNTESTED in a lab: run them in containerlab or mini-lab before any rollout.',
          '',
        ]
      : []),
    'Still to be set, left undefined on purpose so the roles stop instead of',
    'running with a placeholder:',
    ...MISSING_INPUTS.flatMap((m) => [`  ${m.where}:`, ...m.inputs.map((i) => `    - ${i}`)]),
  ]
  return lines.map((l) => (l ? `# ${l}` : '#')).join('\n') + '\n---\n'
}

export function exportAnsibleInventory(plan: Plan): AnsibleExport {
  const { doc, problems } = deriveInventory(plan)
  return { text: header(plan) + toYaml(doc), problems }
}
